### ISSUE TITLE
adcirc2sel.py - error getIPOBO_IKLE(adcirc_file)

### ISSUE THREAD

**Issue by Brent-Edwards** [pprodano/pputils#2]
See the error messages below:

```
python "I:\dev\pputils\source_code\pputils-master\adcirc2sel.py" -i "I:\dev\pputils\tests\output\rdp_amont_2ans.grd" -p double -o "I:\dev\pputils\tests\output\rdp_amont_2ans.sel"
Traceback (most recent call last):
  File "I:\dev\pputils\source_code\pputils-master\adcirc2sel.py", line 73, in <module>
    n,e,x,y,z,ikle,ppIPOB = getIPOBO_IKLE(adcirc_file)
  File "I:\dev\pputils\source_code\pputils-master\ppmodules\utilities.py", line 544, in getIPOBO_IKLE
    subprocess.call([callstr, adcirc_file, temp_ipobo])
  File "C:\Users\xedwabr\AppData\Local\Continuum\anaconda3\lib\subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\xedwabr\AppData\Local\Continuum\anaconda3\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\xedwabr\AppData\Local\Continuum\anaconda3\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable
```

**Comment by pprodano** [comment]
The way the adcirc2sel.py script was originally made expects the user to place the input and output files in the same directory as pputils. In your case, simply place all your input and output files in "I:\dev\pputils\source_code\pputils-master", and run again. It will work.

I should update this one day. Thanks for the reminder.

**Comment by Brent-Edwards** [comment]
Thanks for the response. Unfortunately, I'm still getting the same errors:

```
python "I:\dev\pputils\source_code\pputils-master\adcirc2sel.py" -i "I:\dev\pputils\source_code\pputils-master\rdp_amont_2ans.grd" -p double -o "I:\dev\pputils\source_code\pputils-master\rdp_amont_2ans.sel"
Traceback (most recent call last):
  File "I:\dev\pputils\source_code\pputils-master\adcirc2sel.py", line 73, in <module>
    n,e,x,y,z,ikle,ppIPOB = getIPOBO_IKLE(adcirc_file)
  File "I:\dev\pputils\source_code\pputils-master\ppmodules\utilities.py", line 544, in getIPOBO_IKLE
    subprocess.call([callstr, adcirc_file, temp_ipobo])
  File "C:\Users\xedwabr\AppData\Local\Continuum\anaconda3\lib\subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\xedwabr\AppData\Local\Continuum\anaconda3\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\xedwabr\AppData\Local\Continuum\anaconda3\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable
```

**Comment by Brent-Edwards** [comment]
Accidentally closed issue.

**Comment by pprodano** [comment]
The problem likely results that you are specifying a path instead of a file. Assuming your terminal is in "I:\dev\pputils\source_code\pputils-master", run the following:

python adcirc2sel.py -i rdp_amont_2ans.grd -p double -o rdp_amont_2ans.sel

Make sure the file "I:\dev\pputils\source_code\pputils-master/rdp_amont_2ans.grd" exists, and is in the correct format. This is how all original scripts were meant to run. 

Let me know if it works for you.

**Comment by Brent-Edwards** [comment]
The script executed and produced a .cli and .sel file. GDAL/QGIS can read the .sel file; however, something is wrong as all the elements seem to be "stacked" on top of each other.

**Comment by pprodano** [comment]
There has been no response from the user in the past month. This leads me to think that the error above relates to a bad mesh, and not an issue with adcirc2sel.py. 

Closing the issue.
